

// No rascunho que fiz, ao tentar executar o código com as suas especificações, o atributo "balance" (aqui é 50), é entendido como 0 e entra na exceção
import * as self from "../utils/utils"
import { Conta } from "../cls/conta"

// const sample: Conta = new Conta("1000", -10)
// self.bank.inserir(sample)
// console.log(sample.balance)
console.log(Number("-1"))